<a href="https://colab.research.google.com/github/Gigiasu/MAT-421/blob/main/ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.2.1 Linear Combinations

Linear combination is a vector made by multiplying individual vectors by a scaler and adding the resultant vectors. A linear subspace is a result of linear combinations.

In the example below we will write the vector [2,6,2] as a linear combination of two vectors.



In [4]:
import numpy as np
vector_one=np.array([1,2,1])
vector_two=np.array([0,2,0])

x=vector_one*2
y=vector_two*1

z=np.array([2,6,2])

result=x+y
print(result)
print(result==z)

[2 6 2]
[ True  True  True]


1.2 Linear independence and dimension

A set of vectors are linearly independent if none of them can be written as a combination of the other. If all the vectors were to be multiplied by some scaler and added to get the zero vector, to be linearly independent, the only possible scaler must be zero. 

Basis: set of vectors that generates all elements of the vector space and the vectors in the set are linearly independent

The dimension theorem: Let U be a linear subspace of V. Any basis and bases of U has the same number of elements. This number is called the dimension 

For the example below we will take the vectors [4,3,5], [5,2,1], and [4,7,8] and see if they are linearly independent by setting them equal to the zero vector. If the solution is [0,0,0] then they are linearly independent. The equation will be c1[4,3,5]+c2[5,2,1]+c3[4,7,8]=[0,0,0]

In [5]:
A=np.array([[4,3,5], [5,2,1], [4,7,8]])
y=np.array([0,0,0])
x=np.linalg.solve(A,y)
print(x)

[0. 0. 0.]


1.2 Orthonormal basis

Inner product: ⟨u,v⟩ = u·v

Orthonomal: A list of vectors s {u1,...,um}is orthonormal if all of the vectors are pairwise orthogonal and each has a norm of 1

Orthogonal Projection: Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm. The orthogonal porjection of v ∊ V on U is Pu v =∑(j=1)⟨v,qj⟩qj

Best Approximation Theorem: Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm and let v∈V. For any u∈U, ∥v−PU v∥ ≤ ∥v−u∥.


Gram-Schmidt process: Gram_Schmidt is used to obtain an orthonormal basis. Let a1,...,am in Rn be linearly independent. Then there exist an orthonormal basis q1,...,qm of span(a1,...,am).

1.2 Eigenvalues and Eigenvectors

Eigenvalue: Let A be a square matrix in the real number system. Then λ ∈ R is an eigenvalue of A if there exists a nonzero vector x ̸= 0 such that Ax = λx. The vector x is refered to as the eigenvector

In the example below we will explore eigenvalues and eigenvectors




In [9]:
import numpy as np
from numpy.linalg import eig
x = np.array([ [0, 2], [2, 3] ])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


1.3 Linear Regression

QR decomposition: QR decomposition breaks down a matrix A into two matrix that when multipied together, A = QR, producte matrix A. These matrices can be derived from the Gram-Schimdt process. 

In [11]:
import numpy as np
from numpy.linalg import qr
x = np.array([[1, 2], [3, 4]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

y = np.dot(Q, R)
print('QR:', y)

iterations = [1, 20]
for i in range(20):
    Q,R = qr(x)
    x = np.dot(R, Q)
    if i+1 in iterations:
        print(f'Iteration {i+1}:')
        print(x)

Q: [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R: [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
QR: [[1. 2.]
 [3. 4.]]
Iteration 1:
[[ 5.2  1.6]
 [ 0.6 -0.2]]
Iteration 20:
[[ 5.37228132e+00 -1.00000000e+00]
 [ 5.93103358e-23 -3.72281323e-01]]


Least Square problems

The system Ax=b is often inconsistent. Thus, we look to use Ax to approximate b. In this case we are interested in overdetermined systems wehre n>m. With the QR breakdown we can get Rx*=Q^T b which can be solved by backwards substitution. 